language: c

cache:
    - ccache
    - pip

compiler:
    - gcc

before_install:
    - sudo add-apt-repository --yes ppa:vala-team
    - sudo apt-get update --quiet
    - sudo apt-get install --yes --force-yes valac-0.26 libglib2.0-bin
      libglib2.0-dev libsoup2.4-dev libfcgi-dev python-pip valadoc
    - sudo pip install cpp-coveralls sphinx PyYAML

before_script:
    - ./waf configure CFLAGS='-fprofile-arcs -ftest-coverage' VALAFLAGS='--enable-checking --debug'
    - ./waf build

script:
    - ./build/tests/tests
    - valadoc --pkg=glib-2.0 --pkg=gio-2.0 --pkg=gio-unix-2.0 --pkg=libsoup-2.4
      --pkg=fcgi --target-glib=2.32 --directory=build/apidocs
      --vapidir=/usr/share/vala-0.26/vapi --vapidir=src/vsgi-fastcgi
      src/**/*.vala

after_success:
    - coveralls --repo-token $COVERALLS_TOKEN --build-root build
                --exclude build/examples --exclude build/tests
